import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import ThemeRegistry from "~/theme/ThemeRegistry";

export const metadata: Metadata = {
  title: "Article Review Workspace",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={geist.variable}>
        <TRPCReactProvider>
          <ThemeRegistry>{children}</ThemeRegistry>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
